# 自定义的代理规则 每行一个规则

##develop
DOMAIN-SUFFIX,v2ex.com,PROXY
DOMAIN-SUFFIX,linux.do,PROXY
DOMAIN-SUFFIX,dogyun.com,PROXY
DOMAIN-SUFFIX,trakt.tv,PROXY

##porn
DOMAIN-SUFFIX,missav.ws,PROXY

##music
DOMAIN-SUFFIX,1music.cc,PROXY

##vercel
DOMAIN,gpt.chuanfang.org,PROXY
DOMAIN,prompt.chuanfang.org,PROXY
DOMAIN,reference.chuanfang.org,PROXY
DOMAIN,linux.chuanfang.org,PROXY
DOMAIN,regex.chuanfang.org,PROXY
DOMAIN,panhub.chuanfang.org,PROXY
DOMAIN,libretv.chuanfang.org,PROXY
DOMAIN,blog.chuanfang.org,PROXY

##NET
DOMAIN-SUFFIX,fofa.info,PROXY
