# 自定义的代理规则 每行一个规则

##develop
DOMAIN-SUFFIX,v2ex.com,PROXY
DOMAIN-SUFFIX,linux.do,PROXY
DOMAIN-SUFFIX,dogyun.com,PROXY
DOMAIN-SUFFIX,trakt.tv,PROXY

##porn
DOMAIN-SUFFIX,missav.ws,PROXY

##music
DOMAIN-SUFFIX,1music.cc,PROXY

##vercel
DOMAIN,gpt.chuanfang.org
DOMAIN,prompt.chuanfang.org
DOMAIN,reference.chuanfang.org
DOMAIN,linux.chuanfang.org
DOMAIN,regex.chuanfang.org
DOMAIN,panhub.chuanfang.org
DOMAIN,libretv.chuanfang.org
DOMAIN,blog.chuanfang.org

##other
DOMAIN-SUFFIX,fofa.info,PROXY
