# 代理加速规则

##google
RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Shadowrocket/Google/Google.list,PROXY

##youtube music
RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Shadowrocket/YouTubeMusic/YouTubeMusic.list,PROXY

##youtube
RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Shadowrocket/YouTube/YouTube.list,PROXY

##telegram
RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Shadowrocket/Telegram/Telegram.list,PROXY

##github
RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Shadowrocket/GitHub/GitHub.list,PROXY

##ai
RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Shadowrocket/OpenAI/OpenAI.list,PROXY
RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Shadowrocket/Gemini/Gemini.list,PROXY
RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Shadowrocket/Claude/Claude.list,PROXY
DOMAIN-SUFFIX,grok.com,PROXY
DOMAIN-SUFFIX,perplexity.ai,PROXY

##netflix
RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Shadowrocket/Netflix/Netflix.list,PROXY

##disney+
RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Shadowrocket/Disney/Disney.list,PROXY

##twitter
RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Shadowrocket/Twitter/Twitter.list,PROXY

##Instagram
RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Shadowrocket/Instagram/Instagram.list,PROXY

##Facebook
RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Shadowrocket/Facebook/Facebook.list,PROXY

##Microsoft
RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Shadowrocket/Microsoft/Microsoft.list,PROXY

##TestFlight
RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Shadowrocket/TestFlight/TestFlight.list,PROXY

##苹果推送
RULE-SET,https://raw.githubusercontent.com/QuixoticHeart/rule-set/refs/heads/ruleset/loon/apns.list,PROXY
IP-CIDR,17.0.0.0/8,PROXY,no-resolve

# PornHub
DOMAIN-SUFFIX,pornhub.com,PROXY
DOMAIN-SUFFIX,phncdn.com,PROXY

##Missav
DOMAIN-SUFFIX,missav.ws,PROXY
DOMAIN-SUFFIX,missav.live,PROXY

##spankbang
DOMAIN-SUFFIX,spankbang.com,PROXY

# xVideos
DOMAIN-SUFFIX,xvideos.com,PROXY
DOMAIN-SUFFIX,xvideos-cdn.com,PROXY

# xHamster
DOMAIN-SUFFIX,xhamster.com,PROXY
DOMAIN-SUFFIX,xhcdn.com,PROXY

# RedTube
DOMAIN-SUFFIX,redtube.com,PROXY

# YouPorn
DOMAIN-SUFFIX,youporn.com,PROXY

# Tube8
DOMAIN-SUFFIX,tube8.com,PROXY

# OnlyFans
DOMAIN-SUFFIX,onlyfans.com,PROXY

RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Shadowrocket/GlobalMedia/GlobalMedia.list,PROXY
