name: 部署shadowrocket配置

on:
  push:
  workflow_dispatch:
  # schedule:
  #   - cron: '0 22 * * *'

jobs:
  gist:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0

      # set python
      - name: Set up Python 3.8
        uses: actions/setup-python@v2.2.2
        with:
          python-version: 3.8

      # install requirements
      - name: Install requirements
        run: |
          pip install -r requirements.txt

      # prepare config
      - name: prepare
        run: |
          python main.py

      - name: 黑名单规则
        uses: exuanbo/actions-deploy-gist@v1.1.4
        with:
          token: ${{ secrets.GH_TOKEN }}
          gist_id: ${{ secrets.BLACK_GIST_ID }}
          file_path: dist/shadowrocket_black.conf

      - name: 黑名单规则(广告拦截)
        uses: exuanbo/actions-deploy-gist@v1.1.4
        with:
          token: ${{ secrets.GH_TOKEN }}
          gist_id: ${{ secrets.BLACK_AD_GIST_ID }}
          file_path: dist/shadowrocket_black_ad.conf

      - name: 黑名单规则(加速)
        uses: exuanbo/actions-deploy-gist@v1.1.4
        with:
          token: ${{ secrets.GH_TOKEN }}
          gist_id: ${{ secrets.BLACK_ACCELERATE_GIST_ID }}
          file_path: dist/shadowrocket_black_accelerate.conf

      - name: 黑名单规则(加速+广告拦截)
        uses: exuanbo/actions-deploy-gist@v1.1.4
        with:
          token: ${{ secrets.GH_TOKEN }}
          gist_id: ${{ secrets.BLACK_ACCELERATE_AD_GIST_ID }}
          file_path: dist/shadowrocket_black_accelerate_ad.conf

      - name: 白名单规则
        uses: exuanbo/actions-deploy-gist@v1.1.4
        with:
          token: ${{ secrets.GH_TOKEN }}
          gist_id: ${{ secrets.WHITE_GIST_ID }}
          file_path: dist/shadowrocket_white.conf

      - name: 白名单规则(广告拦截)
        uses: exuanbo/actions-deploy-gist@v1.1.4
        with:
          token: ${{ secrets.GH_TOKEN }}
          gist_id: ${{ secrets.WHITE_AD_GIST_ID }}
          file_path: dist/shadowrocket_white_ad.conf

      - name: 白名单规则(加速)
        uses: exuanbo/actions-deploy-gist@v1.1.4
        with:
          token: ${{ secrets.GH_TOKEN }}
          gist_id: ${{ secrets.WHITE_ACCELERATE_GIST_ID }}
          file_path: dist/shadowrocket_white_accelerate.conf

      - name: 白名单规则(加速+广告拦截)
        uses: exuanbo/actions-deploy-gist@v1.1.4
        with:
          token: ${{ secrets.GH_TOKEN }}
          gist_id: ${{ secrets.WHITE_ACCELERATE_AD_GIST_ID }}
          file_path: dist/shadowrocket_white_accelerate_ad.conf
