name: 部署shadowrocket配置

on:
  push:
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0

      # set python
      - name: Set up Python 3.8
        uses: actions/setup-python@v2.2.2
        with:
          python-version: 3.8

      # install requirements
      - name: Install requirements
        run: |
          pip install -r requirements.txt

      # prepare config
      - name: prepare
        working-directory: ./src
        run: |
          python main.py

      - name: Deploy to Gist
        uses: exuanbo/actions-deploy-gist@v1.1.4
        with:
          token: ${{ secrets.GH_TOKEN }}
          gist_id: ${{ secrets.GIST_ID }}
          file_path: default.conf
          file_type: text
